### ISSUE TITLE
Error when opening Mac build

### ISSUE THREAD

**Issue by OTCsp00kyOBE** [EricSouther/Phosphortron#2]
I get this error when trying to open the Mac build:

“Phosphortron” is damaged and can’t be opened. You should move it to the Bin.

Catalina 10.15.7

**Comment by OTCsp00kyOBE** [comment]
> I get this error when trying to open the Mac build:
> 
> “Phosphortron” is damaged and can’t be opened. You should move it to the Bin.
> 
> Catalina 10.15.7

Just me on my noob tip. Did some Googling to work out how to run the app. It's a lot of fun, thank you 👍

**Comment by rileyjshaw** [comment]
This crashes on my M1 Mac running Ventura 13.3.1, but I was able to get it running on an older computer using the following terminal command:

```
xattr -cr ~/Downloads/Phosphortron.app # Or wherever it’s saved.
```

Hope this helps someone out!
